# Generated by Django 2.2.10 on 2022-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220116_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizresults',
            name='user_answer_text',
            field=models.TextField(max_length=255),
        ),
    ]
