# Generated by Django 2.2.10 on 2022-01-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220116_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizresults',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
