# Generated by Django 2.2.10 on 2022-01-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220116_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Start Date'),
        ),
    ]
