# Generated by Django 2.2.10 on 2022-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220116_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(auto_now=True, default=(2020, 10, 10, 10, 10, 10), verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
